---
- hosts: webserv

  vars_files:
    - ../../../vars/global.yml
    - ../../../vars/dependencies.yml

  tasks:
    - name: set timezone to Europe/Berlin
      timezone:
        name: Europe/Berlin
      become: yes
      become_method: sudo

    - name: Creating required directory structure
      file:
        path: "{{ required_directory_structure }}"
        state: directory
        mode: 0777
      become: yes

    - name: "Creating required directory structure for {{ ansible_user_id }}"
      file:
        path: "/opt/venvs"
        state: directory
        owner: "{{ ansible_user_id }}"
        mode: 0744
      become: yes

    - name: upgrade all packages
      yum:
        name: "*"
        state: latest
      become: yes

    - name: Install core packages
      yum:
        name: "{{ item.name }}"
        state: present
        update_cache: yes
      loop: "{{ core_packages }}"
      become: yes

    - name: Install pip
      command: "pip3 install pip"
      become: yes

    - name: Update alternatives for pip to pip3
      command: "update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1"
      become: yes

    - name: Install core python packages
      pip:
        name: "{{ item.name }}"
        state: present
        extra_args: --no-cache-dir
      ignore_errors: true
      loop: "{{ default_pip_package }}"
      register: command_result
      become: yes
