---
- hosts: webserv

  vars_files:
    - ../../../vars/global.yml
    - ../../../vars/dependencies.yml

  tasks:
    - name: set timezone to Europe/Berlin
      timezone:
        name: Europe/Berlin
      become: yes
      become_method: sudo

    - name: Creating required directory structure
      file:
        path: "{{ required_directory_structure }}"
        state: directory
        mode: 0777
      become: yes

    - name: "Creating required directory structure"
      file:
        path: "/opt/venvs"
        state: directory
        owner: "{{ ansible_user_id }}"
        mode: 0744
      become: yes

    - name: Install core packages
      yum:
        name: "{{ item.name }}"
        state: present
        update_cache: yes
      loop: "{{ core_packages }}"
      become: yes

    # - name: Install pip
    #   yum:
    #     name: python-pip
    #     update_cache: yes
    #     state: present

    - name: Install core python packages
      pip:
        name: "{{ item.name }}"
        state: present
        extra_args: --no-cache-dir
      ignore_errors: true
      loop: "{{ default_pip_package }}"
      register: command_result

    - debug:
        msg: "{{item.msg}}"
      failed_when: '"finished with status ''done''" not in item.msg'
      when: item.msg  is defined
      with_items: "{{ command_result.results }}"
