docker__default_pip_packages:
  - name: "docker"
    state: "present"
    version: "4.0.2"
  - name: "docker-compose"
    state: "present"
    version: "1.24.1"

ip_addr: ""


# docker dns path for docker.io package ( changed at ubuntu 14.04 from docker to docker.io )
setup: "node-ssl"
docker_swarm: ""#"127.0.0.1"


docker__version: "18.09.5"

docker__channel: ["stable"]

docker__package_dependencies:
  - "yum-transport-https"
  - "ca-certificates"
  - "cron"
  - "gnupg2"
  - "software-properties-common"

docker__yum_key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
docker__yum_key_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker__yum_repository: >
  deb [arch=amd64]
  https://download.docker.com/linux/{{ ansible_distribution | lower }}
  {{ ansible_distribution_release }} {{ docker__channel | join (' ') }}


cert_dir: /opt/certs/docker/
app_name: docker