---
- name: Create required directory structure /home/naveed/data/work/projects/ultratendency/bunnycrm/deploy-ansible/bunnycrm/
  file:
    path: /home/naveed/data/work/projects/ultratendency/bunnycrm/deploy-ansible/bunnycrm/
    state: directory

- git:
    repo: 'git@github.com:naveedkamran/bunnycrm.git'
    dest: /home/naveed/data/work/projects/ultratendency/bunnycrm/deploy-ansible/bunnycrm/
    update: yes
    version: dev

- name: Updating file /home/naveed/data/work/projects/ultratendency/bunnycrm/deploy-ansible/bunnycrm/source/server-java/src/main/resources/application.properties
  copy:
    src: ./server-data/production/server-java/database.properties
    dest: /home/naveed/data/work/projects/ultratendency/bunnycrm/deploy-ansible/bunnycrm/source/server-java/src/main/resources/

- name: Updating file /home/naveed/data/work/projects/ultratendency/bunnycrm/deploy-ansible/bunnycrm/source/server-java/src/main/resources/META-INF/spring/properties/database.properties
  copy:
    src: ./server-data/production/server-java/database.properties
    dest: /home/naveed/data/work/projects/ultratendency/bunnycrm/deploy-ansible/bunnycrm/source/server-java/src/main/resources/META-INF/spring/properties/

- name: Updating file /home/naveed/data/work/projects/ultratendency/bunnycrm/deploy-ansible/bunnycrm/source/server-controller/src/main/resources/META-INF/spring/properties/database.properties
  copy:
    src: ./server-data/production/server-java/database.properties
    dest: /home/naveed/data/work/projects/ultratendency/bunnycrm/deploy-ansible/bunnycrm/source/server-controller/src/main/resources/META-INF/spring/properties/

- name: Running server-java gradle clean build
  command: "chdir=/home/naveed/data/work/projects/ultratendency/bunnycrm/deploy-ansible/bunnycrm/source/server-java gradle clean build -x test"
  ignore_errors: no

- name: Running controller gradle clean build
  command: "chdir=/home/naveed/data/work/projects/ultratendency/bunnycrm/deploy-ansible/bunnycrm/source/server-controller gradle clean build -x test"
  ignore_errors: no

# - name: Running server-java gradle clean build
#   command: "gradle clean build  -x test -p /home/naveed/data/work/projects/ultratendency/bunnycrm/deploy-ansible/bunnycrm/source/server-java"
