---
#not used

- name: Set swarm port
  set_fact:
    swarm_port: 3375
  when: setup == "node"

- name: Set swarm tls port
  set_fact:
    swarm_port: 3376
  when: setup == "node-ssl"

- name: Copy nodelist to swarm host if it's not already present
  copy:
    src: "nodelist"
    dest: "{{ docker_nodelist_path }}/nodelist"
    force: no

- name: Create docker swarm (if not already present)
  docker:
    name: swarm
    image: swarm
    state: present
    restart_policy: always
    ports:
    - "{{ swarm_port }}:{{ swarm_port }}"
    volumes:
    - "{{ docker_ssl_cert_path }}/{{ docker_ssl_cert_path }}"
    - "{{ docker_nodelist_path }}/{{ docker_nodelist_path }}"
  delegate_to: "{{ docker_swarm }}"
