---
- hosts: webserv

  vars_files:
    - ../../../vars/global.yml
    - ../../../vars/dependencies.yml
    - ../vars/main.yml

  tasks:
    # CHECK THE ARCH
    # - name: Install a .deb package from the internet.
    #   apt:
    #     deb: https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_19.03.1~3-0~ubuntu-bionic_amd64.deb
    #   become: yes
    - name: Install Docker.
      package:
        name: "{{ docker_package }}"
        state: "{{ docker_package_state }}"
      notify: restart docker

    - name: Ensure Docker is started and enabled at boot.
      service:
        name: docker
        state: "{{ docker_service_state }}"
        enabled: "{{ docker_service_enabled }}"

    - name: Ensure handlers are notified now to avoid firewall conflicts.
      meta: flush_handlers
