# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes_bcrm = [
  {
    :name => "bcrm",
    #:box => "ubuntu/disco64",
    :box => "ubuntu/bionic64",
    :ip => '192.168.99.101',
    :cpu => "100",
    :ram => "3000"
  }
]

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|

  boxes_bcrm.each do |box|
    config.vm.define box[:name] do |vms|
      vms.vm.box = box[:box]
      vms.vm.hostname = :name

      vms.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--cpuexecutioncap", box[:cpu]]
        v.customize ["modifyvm", :id, "--memory", box[:ram]]
      end

      vms.vm.network :private_network, ip: box[:ip]
      #vms.vm.network "forwarded_port", guest: 5000, host: 5000, protocol: "tcp", auto_correct: true

      # config.ssh.username = 'vagrant'
      # config.ssh.password = 'vagrant'
      config.ssh.insert_key = false

      config.vm.provision "shell", inline: <<-SHELL
        sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
        service ssh restart
      SHELL

      config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
        echo #{ssh_pub_key} >> /home/ubuntu/.ssh/authorized_keys
        # sudo yum -y install python-minimal
        SHELL
      end

    end
  end

end
